{
  "version": 2,
  "builds": [
    {
      "src": "server.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "server.js"
    }
  ],
  "env": {
    "MERCADOPAGO_ACCESS_TOKEN": "@mercadopago_access_token",
    "FRONTEND_URL": "@frontend_url"
  }
}
